name: twoot on a schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "4 1,5,9,13,17,21 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    environment: twoot
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.9.1"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn start
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_TOKEN_ORIG: ${{ secrets.MASTODON_TOKEN_ORIG }}
          TWITTER_ACCESS_KEY: ${{ secrets.TWITTER_ACCESS_KEY }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
